language: go

notifications:
  email: false

go:
  - 1.9
  - tip

install:
  - go get github.com/asaskevich/EventBus
  - go get github.com/ugorji/go/codec
  - go get github.com/zeromq/gomq
  - go get github.com/google/uuid
  - go get github.com/olekukonko/tablewriter
  - go get github.com/stretchr/testify/assert
  - go get github.com/shirou/gopsutil
  - go get golang.org/x/sys/unix

script:
  - go test -timeout 1m -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
